server:
  port: 8080
spring:
  application:
    name: cheatsheet
  datasource:
    url: jdbc://localhost:5432/cheatsheet
    username: myuser
    password: secret
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
  flyway:
    default-schema: public
    enabled: true
