create table cheat_sheet
(
    id          bigint generated by default as identity
        primary key,
    category    varchar(255),
    description varchar(255),
    language    varchar(255),
    title       varchar(255),
    url         varchar(255)
);


insert into cheat_sheet(language, category, title, description, url)
values ('Java', 'Monitoring', 'Spectator', 'Client library for collecting metrics.',
        'https://github.com/Netflix/spectator'),
       ('Java', 'Gateway', 'Apache ShenYu',
        'Apache ShenYu is a Java native API Gateway for service proxy, protocol conversion and API governance.',
        'https://github.com/apache/shenyu'),
       ('Go', 'Database', 'TiDB',
        'TiDB is an open-source, cloud-native, distributed, MySQL-Compatible database for elastic scale and real-time analytics',
        'https://github.com/pingcap/tidb');