create table category
(
    id          bigint generated by default as identity
        primary key,
    name        varchar(255),
    description varchar(255)
);
create index category_name_idx on category (name);

create table language
(
    id   bigint generated by default as identity
        primary key,
    name varchar(255)
);
create index language_name_idx on language (name);


create table cheat_sheet
(
    id          bigint generated by default as identity
        primary key,
    category_id bigint not null
        constraint fka01tt5h03j7rl5qojdi7t32x5
            references category,
    language_id bigint not null
        constraint fk16ulsxp5xgg0b6jg8rd9a7nlp
            references language,
    description varchar(255),
    title       varchar(255),
    url         varchar(255)
);

insert into category(name, description)
values ('Monitoring', 'Tools that observe/monitor applications in production'),
       ('Gateway', 'Everything related to gateways'),
       ('Database', 'Everything that simplifies interactions with the database'),
       ('Testing', 'Tools that test from model to the view'),
       ('Linter', 'Tools that provide linter'),
       ('Dependency Injection', 'Libraries that provide DI'),
       ('Configuration', 'Libraries that provide external configuration'),
       ('Messaging',
        'Tools that help send messages between clients to ensure protocol independency'),
       ('API docs', 'Tools specifically for creating API docs');

insert into language(name)
values ('Java'),
       ('Go'),
       ('Rust');

