insert into cheat_sheet(language, category, title, description, url)
values ('Go', 'API docs', 'Swag ',
        'Automatically generate RESTful API documentation with Swagger 2.0 for Go.',
        'https://github.com/swaggo/swag'),
       ('Go', 'API docs', 'oapi-codegen ',
        'Generate Go client and server boilerplate from OpenAPI 3 specifications',
        'https://github.com/oapi-codegen/oapi-codegen'),
       ('Go', 'Configuration', 'envconfig ',
        'Golang library for managing configuration data from environment variables',
        'https://github.com/kelseyhightower/envconfig'),
       ('Go', 'Dependency Injection', 'Wire', 'Compile-time Dependency Injection for Go',
        'https://github.com/google/wire'),
       ('Go', 'Dependency Injection', 'IOC-golang', 'A Golang depenedency injection framework, helps developers to build any go application',
        'https://github.com/alibaba/IOC-golang'),
       ('Go', 'Testing', 'Testify', 'A toolkit with common assertions and mocks that plays nicely with the standard library',
        'https://github.com/stretchr/testify'),
       ('Go', 'Testing', 'moq', 'Interface mocking tool for go generate',
        'https://github.com/matryer/moq'),
       ('Go', 'Testing', 'gomock', 'GoMock is a mocking framework for the Go programming language',
        'https://github.com/uber-go/mock'),
       ('Go', 'Linter', 'golangci-lint', 'Fast linters runner for Go',
        'https://github.com/golangci/golangci-lint'),
       ('Go', 'Messaging', 'NSQ', 'A realtime distributed messaging platform',
        'https://github.com/nsqio/nsq');
